# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-28 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booklet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('reply_1', models.CharField(max_length=400, verbose_name='Отввет_1')),
                ('reply_2', models.CharField(max_length=400, verbose_name='Отввет_2')),
                ('reply_3', models.CharField(max_length=400, verbose_name='Отввет_3')),
                ('reply_4', models.CharField(max_length=400, verbose_name='Отввет_4')),
                ('reply_5', models.CharField(max_length=400, verbose_name='Отввет_5')),
                ('right', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=1, verbose_name='Правильный ответ')),
            ],
        ),
        migrations.CreateModel(
            name='Booklets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название буклета, прим. Буклет 2016 року')),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название класа, прим. КРОК 1 - Стоматология')),
            ],
        ),
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='прим. Українською мовою')),
            ],
        ),
        migrations.AddField(
            model_name='booklets',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apka.Classes'),
        ),
        migrations.AddField(
            model_name='booklets',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apka.Lang'),
        ),
        migrations.AddField(
            model_name='booklet',
            name='booklet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apka.Booklets'),
        ),
    ]
