# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Название класа, прим. КРОК 1 - атология'),
        ),
    ]
