# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0002_auto_20170302_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklet',
            name='booklet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apka.Booklets'),
        ),
        migrations.AlterField(
            model_name='booklets',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apka.Classes'),
        ),
    ]
