# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0003_auto_20170302_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('link', 'Link'), ('title', 'Title')], max_length=300, verbose_name='')),
                ('t1', models.CharField(max_length=300, verbose_name='')),
                ('t2', models.CharField(max_length=300, verbose_name='')),
                ('t3', models.CharField(max_length=300, verbose_name='')),
                ('t4', models.CharField(max_length=300, verbose_name='')),
                ('t5', models.CharField(max_length=300, verbose_name='')),
                ('t6', models.CharField(max_length=300, verbose_name='')),
                ('t7', models.CharField(max_length=300, verbose_name='')),
                ('t8', models.CharField(max_length=300, verbose_name='')),
                ('t9', models.CharField(max_length=300, verbose_name='')),
                ('t10', models.CharField(max_length=300, verbose_name='')),
                ('lang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apka.Lang')),
            ],
        ),
    ]
