# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0004_panel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='t10',
        ),
    ]
