# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0005_remove_panel_t10'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='type',
        ),
    ]
