# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0006_remove_panel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='bottomLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1', models.CharField(max_length=300, verbose_name='Розпочати тестування ')),
                ('t2', models.CharField(max_length=300, verbose_name='Розповчати навчання')),
                ('t3', models.CharField(max_length=300, verbose_name='Переглянути базу')),
                ('lang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apka.Lang')),
            ],
        ),
    ]
