# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-04 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0008_auto_20170303_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='eng',
            field=models.CharField(max_length=300, null=True, verbose_name='Английский'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='rus',
            field=models.CharField(max_length=300, null=True, verbose_name='Русский'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='ukr',
            field=models.CharField(max_length=300, null=True, verbose_name='Украинский'),
        ),
    ]
