# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-05 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0012_auto_20170305_0356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notone', models.CharField(max_length=500, verbose_name='Ни одного теста не найдено')),
                ('error_1', models.CharField(max_length=500, verbose_name='нет ошибок')),
                ('error_2', models.CharField(max_length=500, verbose_name='Зарегайся мразь')),
                ('save_1', models.CharField(max_length=500, verbose_name='Нихера не сохранил')),
                ('save_2', models.CharField(max_length=500, verbose_name='Войди сука шоб сохранять')),
                ('login', models.CharField(max_length=500, verbose_name='Зайди в соцсеть пидор')),
                ('lang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apka.Lang')),
            ],
        ),
    ]
