# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-05 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0013_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='t3',
        ),
    ]
