# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-05 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0014_remove_panel_t3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.CharField(max_length=300, verbose_name='путь')),
                ('classes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apka.Classes')),
                ('lang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apka.Lang')),
            ],
        ),
    ]
