# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-06 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0015_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='notDown',
            field=models.CharField(max_length=500, null=True, verbose_name='Скачать'),
        ),
    ]
